services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_started
    ports:
      - '80:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=REPLACEME
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    ports:
      - '80:5000'
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./data:/usr/src/app/data
