services:
  server:
    build:
      context: https://github.com/fruitcake514/saas-budget.git#main:/server
      dockerfile: Dockerfile
    volumes:
      # Persistent storage for server-side uploads (e.g., CSV imports)
      - ./uploads:/usr/src/app/uploads
    ports:
      - "5000:5000"
    environment:
      - DB_USER=budget
      - DB_HOST=db
      - DB_DATABASE=saasbudget
      - DB_PASSWORD=saasbudget
      - DB_PORT=6161
      - JWT_SECRET=#Replace Me
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    # Set user and group for the server process inside the container
    user: "xxx:xxx"
    depends_on:
      db:
        condition: service_healthy
  client:
    build:
      context: https://github.com/fruitcake514/saas-budget.git#main:/client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_started
  db:
    build:
      context: https://github.com/fruitcake514/saas-budget.git#main:/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: saasbudget
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: saasbudget
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # Set user and group for the postgres process inside the container
    user: "xxx:xxx"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget -d saasbudget"]
      interval: 5s
      timeout: 5s
      retries: 5
